### ISSUE TITLE
throws me warning

### ISSUE THREAD

**Issue by whynot3k** [openbullet/openbullet-api#1]
i went to setup on windows server with the sdk installed and when i connect to localhost:5000 i get error 
"warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect."
i looked into it and couldnt find a post or anything on how to fix it in this case was hoping for some help

**Comment by whynot3k** [comment]
also i have a issue accessing my api outside of the host machine ive tried even port forwarding i tried ip:port even dynamichost:port for some reason i just cannot connect from outside if the network could it be from this error it gives me

**Comment by openbullet** [comment]
Hey, can I see what your `Program.cs` looks like? That warn shouldn't be a problem as long as you use HTTP to connect to localhost:5000. If you use HTTPS it won't work, it needs to be set up differently.

**Comment by openbullet** [comment]
As I wrote in the documentation, you should write `.UseUrls("http://0.0.0.0:5000")` in your `Program.cs` file to make it accessible from outside.

**Comment by whynot3k** [comment]
yea dm me on discord?
i can show you it all i tried the precompiled one and even edited it like said in documentation

**Comment by openbullet** [comment]
The edit in the documentation is for localhost only, to make it work you need to switch back to what it was originally.

**Comment by whynot3k** [comment]
okay let me recompile it and show you what i have in  the program.cs

**Comment by openbullet** [comment]
Alright. I prefer to talk here rather than discord because it could help other people in the future as well!

**Comment by whynot3k** [comment]
fair enough i have this rn
`using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace OpenBulletAPI
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseUrls("http://0.0.0.0:5000")
                .UseStartup<Startup>();
    }
}
`

**Comment by whynot3k** [comment]
this didnt work so i changed it to comment it out and still nothing even put my host in aswell still nothing

**Comment by openbullet** [comment]
Yes perfect, your API should be accessible from outside using `http://YOUR_IP:5000/api/configs`. Are you sure your windows firewall has a rule to allow TCP traffic through port 5000? Use https://yougetsignal.com/tools/open-ports/ to test it!

**Comment by whynot3k** [comment]
its not saying i have port access but i made tcp incoming and outgoing aloud with port 5000-5010 just in case

**Comment by openbullet** [comment]
I don't know what else to say, it should work if you have the api running and you test using that online service.

**Comment by whynot3k** [comment]
oh i need it running first hold on lol

**Comment by whynot3k** [comment]
let me recompile it

**Comment by whynot3k** [comment]
Hosting environment: Production
Content root path: C:\Users\Administrator\Desktop\banana
Now listening on: http://0.0.0.0:5000
Application started. Press Ctrl+C to shut down.
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
still get the error and the error happens when i connect to http://localhost:5000/ on the same machine

**Comment by openbullet** [comment]
When you are listening on 0.0.0.0 it means it won't accept connections from localhost but it will accept connections from outside.

**Comment by whynot3k** [comment]
oh okay i will give it a try now

**Comment by whynot3k** [comment]
http://PUBLICIP:5000 so i tried this and secretpassword as a test with panel and it says cannot connect

**Comment by whynot3k** [comment]
http://publicip:5000

**Comment by openbullet** [comment]
the default one is `secretPassword` with a capital P

**Comment by whynot3k** [comment]
yes i know still doesnt work

**Comment by openbullet** [comment]
Okay at this point give me your discord contact I'll give you better help there 😓

**Comment by whynot3k** [comment]
cassell#3994

**Comment by openbullet** [comment]
Issue solved, it was a firewall problem.
