### ISSUE TITLE
request to add first ip binding

### ISSUE THREAD

**Issue by whynot3k** [openbullet/openbullet-api#2]
hey ruri i was wondering if you could add a option for ip binding the first person who uses the key for example lets say i wanna sell a api key well when they use it i wanna make it put the ip that they used for the first api request to then be binded to the ip so only that ip can use it, or for ip i can put "first" as like a place ho;der so that it knows to bind a ip on its own if you could do that id really appreciate it i already have the version that allows ip binding i just dont wanna do manual ip binding

**Comment by meinname** [comment]
translation of request to ruri language:
option for api to do:
if user.IPs = IsNullOrEmpty then user.IPs = ip

**Comment by openbullet** [comment]
Please test https://github.com/openbullet/openbullet-api/commit/ec02fed8cc220dc3fe7e793f3e89cd251e8b51a8 thank you

**Comment by openbullet** [comment]
You need to go to appsettings.json and change the value there

**Comment by whynot3k** [comment]
okay i tried it its not showing into the admin panel with there ip
ima get a database viewer and check that its showing there

**Comment by openbullet** [comment]
I added it, forgot to close this.
