### ISSUE TITLE
API working on local machine not working Outside

### ISSUE THREAD

**Issue by bfx002** [openbullet/openbullet-api#3]
same problem as,
https://github.com/openbullet/openbullet-api/issues/1#issue-437954544
i added firewall rules for inbound and outbound for port 5000 still same issue i can access it on my machine with http://myip:5000 or http://localhost:5000 but dont work on outside machine.
is there any firewall issue or its just me doin smth wrong ?
my program.cs file looks like this.
```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace OpenBulletAPI
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseUrls("http://0.0.0.0:5000")
                .UseStartup<Startup>();
    }
}

```

**Comment by openbullet** [comment]
No, everything looks good. Can you try to use one of the free online services that check if a port is open on your server?

**Comment by bfx002** [comment]
i used, 
https://www.yougetsignal.com/tools/open-ports/
it still says port 5000 is not open

**Comment by openbullet** [comment]
Sorry, it's a problem on your end. The software works fine when used as-is on a vps that I just created, and other people can manage to host it too. If you use linux, maybe take a look at your iptables and firewalld.

**Comment by bfx002** [comment]
is there any way you can take a look at it ? teamviewer discord anything like that ? not a problem if you dont :-)

**Comment by meinname** [comment]
Sorry for asking, but i have no clue about your skills:
Have you forwarded the port on your router (nat/pat Gateway) and are you using the external ip for testing?

Cause for me it works.
also with your test:
<img width="179" alt="image" src="https://user-images.githubusercontent.com/16181408/58370140-66edca00-7f03-11e9-9762-bd1e52253fe1.png">

**Comment by bfx002** [comment]
> Sorry for asking, but i have no clue about your skills:
> Have you forwarded the port on your router and are you using the external ip for testing?
> 
> Cause for me it works.
> also with your test:
> <img alt="image" width="179" src="https://user-images.githubusercontent.com/16181408/58370140-66edca00-7f03-11e9-9762-bd1e52253fe1.png">

i have no experience in this. i just added rules for port 5000 havent know about forwarding. and im doin this on my VPS. and it works for localhost but dont work on outside device when i try to connect with IP:5000

**Comment by meinname** [comment]
Ah, ok VPS. - Well there are multiple users i know of who have it running on their VPS.
Well then very likely firewall. 🤷‍♂
