### ISSUE TITLE
Error when connecting to the server

### ISSUE THREAD

**Issue by ElTande** [openbullet/openbullet-api#4]
Hi, i get this error when i'm trying to connect to my server with OpenBullet, i don't know if it come from the API : 
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
Thanks

**Comment by openbullet** [comment]
That's not an error it's a warning. It's caused by the fact that the solution is set up to work with HTTPS but you're using it through HTTP. Did you set up HTTPS on your domain? Are you using nginx as a reverse proxy?

**Comment by openbullet** [comment]
Oh and by the way, the web api works perfectly even if you disregard that warning, it's just less secure as in the sense that someone sniffing the communication can see cleartext data being sent.
