### ISSUE TITLE
Unable to use --urls command

### ISSUE THREAD

**Issue by Nigel1992** [openbullet/openbullet-api#5]
Hello,

I am trying to use the --urls command but it still launches it with the default options.

pi@raspberrypi:~/Desktop/OpenBulletAPI-0.0.1/OpenBulletAPI-0.0.1 $ dotnet ./OpenBulletAPI.dll --urls "http://0.0.0.0:80"
Hosting environment: Production
Content root path: /home/pi/Desktop/OpenBulletAPI-0.0.1/OpenBulletAPI-0.0.1
Now listening on: http://0.0.0.0:5000
Application started. Press Ctrl+C to shut down.
^CApplication is shutting down...

**Comment by openbullet** [comment]
In case anyone else is struggling with this. Just delete the line with .UseUrls in Program.cs so you can use your own.
