### ISSUE TITLE
error 449

### ISSUE THREAD

**Issue by Sanjay2324** [openbullet/openbullet-api#8]
i am trying to host the api on windows 10 rdp... everything is installed properly but when i start api using dotnet ./OpenBulletAPI.dll i get the message that server started but when i go to my localhost nothing shows up and i get error 404. although i can still able to connect admin panel when i add user and then refresh then everything is deleted automatically and get the error 449

please help me and fix it

**Comment by openbullet** [comment]
Sorry but this API is out of support, please switch to OB2
